### ISSUE TITLE
Code ins Hautprepo überführen

### ISSUE THREAD

**Issue by diegosteinerzli** [diegosteinerzli/m210-counter#2]

**Comment by jimmylevell** [comment]
Archieved original project and migrated this project to org modul-i-ch-109 https://github.com/modul-i-ch-109/counter_kand

**Comment by jimmylevell** [comment]
@diegosteinerzli FYI

**Comment by jimmylevell** [comment]
To reduce redundancy this app can also be archived. @diegosteinerzli
